---
- name: apt-get install machine learning 
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - libatlas-base-dev 
  - mecab
  - swig 
  - nkf 
  - libmecab-dev 
  - mecab-ipadic 
  - python-mecab 
  - g++ 
  - python-numpy
  - python-scipy
  - python-matplotlib
  - ipython
  - ipython-notebook
  - python-pandas
  - python-sympy
  - python-nose 
  - golang 
  - mecab-ipadic-utf8 
  - make 
  - curl 
  - xz-utils
  tags: install_machine_learning

- name: install direnv
  shell: git clone https://github.com/direnv/direnv && cd direnv && make install 
  sudo: yes 
  tags: install direnv

- name: install mecab-ipadic
  shell: aptitude install mecab-ipadic-utf8 
  sudo: yes 
  tags: install mecab-ipadic

- name: download wago 
  shell: wget http://www.cl.ecei.tohoku.ac.jp/resources/sent_lex/wago.121808.pn 
  sudo: yes 
  tags: download wago

- name: download pn trim
  shell: wget http://www.cl.ecei.tohoku.ac.jp/resources/sent_lex/pn.csv.m3.120408.trim 
  sudo: yes 
  tags: download pn trim

- name: pip install machine learning 
  pip: name={{ item }} state=latest executable=/home/vagrant/.pyenv/shims/pip
  with_items:
  - numpy 
  - gensim 
  - cython 
  - ipython 
  - notebook
  - boto==2.35.1 
  - PyYAML 
  - requests==2.9.0 
  - mecab-python3 
  sudo: yes 
  tags: global_python_libraries

- name: pip install machine learning2 
  pip: name={{ item }} state=latest executable=/home/vagrant/.pyenv/shims/pip
  with_items:
  - scipy 
  - sklearn 
  sudo: yes 
  tags: global_python_libraries

- name: install jubatus 
  shell: https://github.com/jubatus/jubatus-installer.git && cd jubatus-installer && ./install.sh && ./install_python.sh
  sudo: yes 
  tags: install jubatus 

- name: source jubatus 
  shell: source /home/vagrant/local/share/jubatus/jubatus.profile 
  sudo: yes 
  tags: install jubatus 

- name: install mecab-ipadic 
  shell: git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
  sudo: yes 
  tags: install mecab 

- name: install mecab-ipadic 
  shell: ./bin/install-mecab-ipadic-neologd -n -y chdir=mecab-ipadic-neologd.git
  sudo: yes 
  tags: install mecab 
