---
  - name: Install Packages
    yum: name={{item}} state=latest
    with_items:
      - php
      - php-mysql
      - mariadb-server
      - MySQL-python

  - name: Start and Enable mariadb
    service: name=mariadb state=started enabled=yes
  - name: Create Database for wordpress
    mysql_db: name={{dbname}} state=present
  - name: Create user for wordpress
    mysql_user: name={{dbuser}} password={{dbpassword}} priv="wordpress.*:ALL" host=localhost state=present

  - name: Get WordPress
    get_url: url=http://ja.wordpress.org/latest-ja.tar.gz dest=/tmp/latest-ja.tar.gz owner=root
    #get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz owner=root
  - name: Unarchive a file
    command: tar zxf /tmp/latest-ja.tar.gz -C /var/www/html creates={{doc_root}}/wordpress
  - name: Copy wp-config.php
    template: src=wp-config.php.j2 dest={{doc_root}}/wordpress/wp-config.php mode=0666
  - name: Change Owner and Group
    command: chown -R apache.apache {{doc_root}}
  - name: Reset value of http_request_timeout
    shell: sed -i -e "s/'http_request_timeout', 5/'http_request_timeout', 20/g" {{doc_root}}/wordpress/wp-includes/class-http.php

  - name: Start and Enable httpd
    service: name=httpd state=started enabled=yes
